# Generated by Django 5.2.7 on 2025-10-22 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('tech', 'Tech'), ('sports', 'Sports'), ('fashion', 'Fashion'), ('Home', 'Home & Kitchen')], default='electronics', max_length=200),
        ),
    ]
