# Generated by Django 5.2.7 on 2025-10-23 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_cartitem_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
