# Generated by Django 5.2.7 on 2025-10-31 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_delete_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category_en',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('tech', 'Tech'), ('sports', 'Sports'), ('fashion', 'Fashion'), ('Home', 'Home & Kitchen')], default='electronics', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='category_fr',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('tech', 'Tech'), ('sports', 'Sports'), ('fashion', 'Fashion'), ('Home', 'Home & Kitchen')], default='electronics', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='category_hi',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('tech', 'Tech'), ('sports', 'Sports'), ('fashion', 'Fashion'), ('Home', 'Home & Kitchen')], default='electronics', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='category_pa',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('tech', 'Tech'), ('sports', 'Sports'), ('fashion', 'Fashion'), ('Home', 'Home & Kitchen')], default='electronics', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_hi',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_pa',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
