# Generated by Django 5.2.7 on 2025-10-31 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_product_category_en_product_category_fr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category_hi',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name_hi',
        ),
    ]
