# Generated by Django 5.2.7 on 2025-10-31 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_remove_product_category_hi_remove_product_name_hi'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category_hi',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('tech', 'Tech'), ('sports', 'Sports'), ('fashion', 'Fashion'), ('Home', 'Home & Kitchen')], default='electronics', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_hi',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
