# Generated by Django 5.2.7 on 2025-10-31 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_product_category_hi_product_name_hi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('tech', 'Tech'), ('sports', 'Sports'), ('fashion', 'Fashion'), ('home', 'Home & Kitchen')], default='electronics', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='category_en',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('tech', 'Tech'), ('sports', 'Sports'), ('fashion', 'Fashion'), ('home', 'Home & Kitchen')], default='electronics', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category_fr',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('tech', 'Tech'), ('sports', 'Sports'), ('fashion', 'Fashion'), ('home', 'Home & Kitchen')], default='electronics', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category_hi',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('tech', 'Tech'), ('sports', 'Sports'), ('fashion', 'Fashion'), ('home', 'Home & Kitchen')], default='electronics', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category_pa',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('tech', 'Tech'), ('sports', 'Sports'), ('fashion', 'Fashion'), ('home', 'Home & Kitchen')], default='electronics', max_length=200, null=True),
        ),
    ]
