# Generated by Django 5.2.7 on 2025-10-27 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_dark_mode_customuser_is_blocked_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['username'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, help_text='Short bio or description.', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='User’s date of birth.', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='location',
            field=models.CharField(blank=True, help_text='User location.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='dark_mode',
            field=models.BooleanField(default=False, help_text="Enables dark mode for the user's dashboard."),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_blocked',
            field=models.BooleanField(default=False, help_text='If true, user cannot log in.'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_private',
            field=models.BooleanField(default=False, help_text='If enabled, only allowed users can view this profile.'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Upload a profile picture.', null=True, upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='two_factor_enabled',
            field=models.BooleanField(default=False, help_text='Enable or disable 2FA for this account.'),
        ),
    ]
