# Generated by Django 5.2.7 on 2025-10-27 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_two_factor_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='otp_code',
            field=models.CharField(blank=True, help_text='Temporary OTP for 2FA verification.', max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='two_factor_enabled',
            field=models.BooleanField(default=False, help_text='Enable or disable 2FA for this account.'),
        ),
    ]
