# Generated by Django 5.2.7 on 2025-10-31 06:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customuser_bio_en_customuser_bio_fr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid username. Unicode letters, numbers, and @/./+/-/_ characters only.', regex='^[\\w.@+\\-_\\u00C0-\\uFFFF]+$')]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username_en',
            field=models.CharField(max_length=150, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid username. Unicode letters, numbers, and @/./+/-/_ characters only.', regex='^[\\w.@+\\-_\\u00C0-\\uFFFF]+$')]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username_fr',
            field=models.CharField(max_length=150, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid username. Unicode letters, numbers, and @/./+/-/_ characters only.', regex='^[\\w.@+\\-_\\u00C0-\\uFFFF]+$')]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username_hi',
            field=models.CharField(max_length=150, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid username. Unicode letters, numbers, and @/./+/-/_ characters only.', regex='^[\\w.@+\\-_\\u00C0-\\uFFFF]+$')]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username_pa',
            field=models.CharField(max_length=150, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid username. Unicode letters, numbers, and @/./+/-/_ characters only.', regex='^[\\w.@+\\-_\\u00C0-\\uFFFF]+$')]),
        ),
    ]
