# Generated by Django 5.2.7 on 2025-10-31 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_customuser_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username_en',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='username_fr',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='username_hi',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='username_pa',
        ),
        migrations.AddField(
            model_name='customuser',
            name='display_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='display_name_en',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='display_name_fr',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='display_name_hi',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='display_name_pa',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
