# Generated by Django 5.2.7 on 2025-11-02 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_customuser_username_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block',
            options={'ordering': ['-created_at'], 'verbose_name': 'Block', 'verbose_name_plural': 'Blocks'},
        ),
    ]
